#!/usr/bin/env bash
#  Bash script that displays the PID, 
#  along with the process name,
#  of processes whose name contain the word bash

for pid in /proc/*/comm; do
    name=$(cat "$pid")
    if [[ "$name" =~ bash ]]; then
        pid_num=$(echo "$pid" | awk -F/ '{print $(NF-1)}')
        echo "$pid_num $name"
    fi
done
